### ISSUE TITLE
Update all docs to point to new config file paths

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#527] opened 2015-11-25 20:20 UTC
For instance here: https://influxdb.com/docs/v0.9/guides/clustering.html

**Comment by beckettsean** [comment] 2015-11-25 22:49
dupe of https://github.com/influxdb/influxdb.com/issues/517

@pauldix can you try hard refreshing? @rossmcdonald fixed all that in https://github.com/influxdb/influxdb.com/pull/514.

If there's still an error, please point out exactly where.

**Closed by beckettsean** 2015-11-25 22:49 UTC

**Comment by pauldix** [comment] 2015-11-25 22:50
ah, sorry about that.
