### ISSUE TITLE
Document how to use retention policies

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#382] opened 2015-10-09 14:36 UTC
I've seen multiple people ask about documentation for how to use retention policies. Should show:

* How to create retention policies of different durations
* How to write data
* How to query data
* Combining with CQs to create different levels of precision

Maybe naming the doc something like Retention Policies and Aggregated Data

**Comment by beckettsean** [comment] 2015-10-09 19:18
closing as duplicate of https://github.com/influxdb/influxdb.com/issues/160

**Closed by beckettsean** 2015-10-09 19:18 UTC

**Comment by pauldix** [comment] 2015-10-09 19:21
Ah, sorry @beckettsean, made your life more difficult. I did a quick search, but didn't see anything. I swear!

**Comment by beckettsean** [comment] 2015-10-09 19:25
No worries, Paul, it's a lot to keep track of. I've had this doc on my list
for three weeks, so it's absolutely acceptable to give me a swift reminder
kick in the rear

On Fri, Oct 9, 2015 at 12:21 PM, Paul Dix <notifications@github.com> wrote:

> Ah, sorry @beckettsean <https://github.com/beckettsean>, made your life
> more difficult. I did a quick search, but didn't see anything. I swear!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb.com/issues/382#issuecomment-146965885>
> .
>



-- 
Sean Beckett
Director of Support and Professional Services
InfluxDB
