### ISSUE TITLE
CREATE DATABASE .... WITH ....

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#540] opened 2015-12-04 14:01 UTC
The `CREATE DATABASE` command has been enhanced, with support for optional commands. This will be in 0.9.6.

https://github.com/influxdb/influxdb/pull/4866

**Comment by beckettsean** [comment] 2015-12-04 19:10
dupe of https://github.com/influxdb/influxdb.com/issues/516

**Comment by beckettsean** [comment] 2015-12-04 19:10
Thanks for the diligence, @otoolep, and sorry my issue title was not clear

**Closed by beckettsean** 2015-12-04 19:10 UTC
