### ISSUE TITLE
Downsamling and remove downsampled data

### ISSUE THREAD

**Issue by benidroe** [influxdb/influxdb.com#397] opened 2015-10-15 13:22 UTC
I try to downsample data. I´ve found this manual:

https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/query_language/continuous_queries.md

In 0.8 there was shard spaces to remove old data. 
How can I downsample my data in 0.9 without keep data that has already downsampled to a different series. I want to remove uncompressed data after it has been compressed.  How can I select default and downsampled data with one query?
I don´t really understand the concept completely.

**Comment by beckettsean** [comment] 2015-10-15 17:51
duplicate of https://github.com/influxdb/influxdb.com/issues/160

> How can I downsample my data in 0.9 without keep data that has already downsampled to a different series. 

Downsampled data must go into a different measurement. There is no way to selectively replace a raw series with a downsampled series. The idea is you create the raw measurement in one retention policy, downsample to a measurement in a different retention policy, and then the raw measurements expire while the downsampled measurements persist.

> How can I select default and downsampled data with one query?

You cannot select data from multiple retention policies at one time. See https://github.com/influxdb/influxdb/issues/2625 for more.

**Closed by beckettsean** 2015-10-15 17:51 UTC
