### ISSUE TITLE
0.9.1: The cluster stopped working after creating a few continuous queries

### ISSUE THREAD

**Issue by junmipan** [influxdb/influxdb.com#132] opened 2015-07-17 19:36 UTC
I am storing collectd metrics in InfluxDB cluster.  There are about 8 measurements.  For each measurement, two continuous queries were created to downsample, one at 15m interval, the other 60m.

The cluster started to experience i/o timeout close to 15-minute mark.
[handoff] 2015/07/17 15:05:22 remote write failed: read message type: read tcp 10.202.39.140:8088: i/o timeout
Eventually InfluxDBClusterClient.write_points() failed with:
InfluxDBClientError: 500: timeout

Sometimes, it's accompanied by a message like "leader not available".

If, as a separate test, I do not create any continuous query, then the same test that stores these measurements can run for a very long time (overnight) without any problem.

Is there any known issue with continuous queries with cluster?  Could you recommend a resolution or workaround for the issue I encountered?

Thanks!

**Comment by beckettsean** [comment] 2015-07-17 20:10
Probable duplicate of https://github.com/influxdb/influxdb/issues/3091. Related to https://github.com/influxdb/influxdb/issues/3257, https://github.com/influxdb/influxdb/issues/3316, https://github.com/influxdb/influxdb/issues/3346, https://github.com/influxdb/influxdb/issues/3213

**Closed by beckettsean** 2015-07-17 20:10 UTC
